
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Skip with git commit -a -m "..." --no-verify
repos:
  - repo: local
    hooks:
      - id: linter-fix
        verbose: true
        pass_filenames: false
        name: format
        entry: uv run poe linter-fix
        language: system
      - id: poe-check
        verbose: true
        pass_filenames: false
        name: check
        entry: uv run poe check
        language: system