FROM apache/airflow:2.10.3

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# default-java is a symlink that works on both amd64 and arm64
ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow
RUN pip install --no-cache-dir pyspark==3.5.1 delta-spark==3.1.0
