services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: nyc_taxi
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../data/init:/docker-entrypoint-initdb.d  # seed SQL au démarrage
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-1}
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  localstack_data: